### ISSUE TITLE
Implement user opt-out feature for email sharing to ColorStack Chapters

### ISSUE THREAD

**Issue by RiosNicholas** [colorstackorg/oyster#138] opened 2024-04-12 19:11 UTC
### Description

ColorStack members who have created their profiles in the Member Directory would be automatically opted-in to share their emails with their local ColorStack Chapters (if they exist), and they could opt out in the settings of their member profile.

### Problem / Value Proposition

As a ColorStack Chapter leader, we often want to provide opportunities to our leaders, specifically catering them to ColorStack National-affiliated members. We cannot identify said members if they haven't posted an introduction or only lurk in Slack, and we cannot request the data without their consent. 

### Additional Context

It would be preferable to make this data available to chapters, at least in the surrounding area, because it is common for ColorStack members to commute to neighboring universities to attend their ColorStack Chapter events.

**Comment by ramiAbdou** [comment] 2024-04-12 21:13
I believe this is a duplicate of #51? If so, @tomas-salgado already implemented this #57!

Should be live here: https://app.colorstack.io/profile/emails.

This feature isn't fully complete though, because we still need to add this opt-out capability to the [application](https://app.colorstack.io/apply)!

**Closed** 2024-04-24 14:46 UTC
Labels: Duplicate ✌️
